development: &defaults
  secret_key_base: b2a82ca36980fa7497b820df58d1ece7fa67e3162db6adf5bf6ddc046d961b390cc02df2cd2a6297b8d46707285404fd5b51731c4c2b2c0a3ebda501371e96e4
  smarty_streets:
    auth_id: f180163b-b2ea-4ef0-b178-a338e625c163
    auth_token: W+oSa76yKtWUDMV+Y48wnSDR9h7kxNQqjOTlXSoWOcko620zx7Po9+WKnP0qT99eGl4ulwrSnHES2b/4ArisuA==
  sunlight:
    api_key: 20bf9b126aee41c889192544dc6bd654
  twilio:
    phone_number: +15412992261
    account_sid: AC66ddaa077a1cf91ae06575dcbe649ff5
    auth_token: 6ac78ed7736278d46ef9e4b8ae15ba62

test:
  <<: *defaults
  secret_key_base: eb2e1f0bae80d82378c1b36eb16f08ecb4e87c5cc731c99445f716a2646c7b6ce82510f68ee79dbe2452ea082803d225d003931af082570e01fbc40965a105d0

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smarty_streets:
    auth_id: <%= ENV["SMARTY_STREETS_AUTH_ID"] %>
    auth_token: <%= ENV["SMARTY_STREETS_AUTH_TOKEN"] %>
  sunlight:
    api_key: <%= ENV["SUNLIGHT_API_ID"] %>
  twilio:
    phone_number: <%= ENV["TWILIO_PHONE_NUMBER"] %>
    account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
    auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
